CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    DOCUMENT_NUMBER VARCHAR(9)
);

CREATE TABLE PRODUCT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    UNITY_PRICE NUMERIC(20,2)
);

CREATE TABLE client_Order (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT (ID),
    ORDER_DATE TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL NUMERIC (20,2)
);

CREATE TABLE ITEM_client_Order (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INTEGER REFERENCES client_Order (ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
    QUANTITY INTEGER
);
CREATE TABLE user (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR (50) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);